import pymysql

conn=pymysql.connect(host='localhost',user='root')
cursor=conn.cursor()
cursor.execute('create database Airlines')
cursor.execute('CREATE TABLE `Airlines`.`Flights` ( `Flight_name` VARCHAR(20) NOT NULL , `Departure` VARCHAR(10) NOT NULL , `Arrival` VARCHAR(10) NOT NULL , `Departure_time` VARCHAR(10) NOT NULL , `Arrival_time` VARCHAR(10) NOT NULL , `Seats` VARCHAR(10) NOT NULL , `Price` VARCHAR(10) NOT NULL , PRIMARY KEY (`Flight_name`)) ENGINE = InnoDB;')
cursor.execute('CREATE TABLE `Airlines`.`Bookings` ( `Booking_id` INT(10) NOT NULL AUTO_INCREMENT ,  `Flight_name` VARCHAR(10) NOT NULL ,  `First_name` VARCHAR(20) NOT NULL ,  `Last_name` VARCHAR(20) NOT NULL ,  `Phone_no` VARCHAR(10) NOT NULL ,  `Email_id` TEXT NOT NULL ,    PRIMARY KEY  (`Booking_id`)) ENGINE = InnoDB;')
#insertStatement = "INSERT INTO `Airlines`.`Flights` (Flight_name,Departure,Arrival,Departure_time,Arrival_time,Seats,Price) VALUES (\"SG-623\",\"MAA\",\"CCU\",\"08:00\",\"10:45\",\"100\",\"4500\")"
cursor.execute('INSERT INTO `Airlines`.`Flights` (Flight_name,Departure,Arrival,Departure_time,Arrival_time,Seats,Price) VALUES ("SG-623","MAA","CCU","08:00","10:45","100","4500")')
cursor.execute('INSERT INTO `Airlines`.`Flights` (Flight_name,Departure,Arrival,Departure_time,Arrival_time,Seats,Price) VALUES ("SG-625","MAA","BEL","10:00","12:45","100","4500")')
cursor.execute('INSERT INTO `Airlines`.`Flights` (Flight_name,Departure,Arrival,Departure_time,Arrival_time,Seats,Price) VALUES ("SG-630","MAA","DEL","08:00","10:45","100","3580")')
cursor.execute('INSERT INTO `Airlines`.`Flights` (Flight_name,Departure,Arrival,Departure_time,Arrival_time,Seats,Price) VALUES ("AI-623","MAA","CCU","22:00","00:45","100","5500")')
cursor.execute('INSERT INTO `Airlines`.`Flights` (Flight_name,Departure,Arrival,Departure_time,Arrival_time,Seats,Price) VALUES ("AI-640","CCU","DEL","12:00","02:45","100","2500")')
cursor.execute('INSERT INTO `Airlines`.`Flights` (Flight_name,Departure,Arrival,Departure_time,Arrival_time,Seats,Price) VALUES ("AI-630","CCU","MAA","06:00","08:45","100","3580")')
cursor.execute('INSERT INTO `Airlines`.`Flights` (Flight_name,Departure,Arrival,Departure_time,Arrival_time,Seats,Price) VALUES ("AI-700","CCU","BEL","22:00","00:45","100","5500")')
cursor.execute('INSERT INTO `Airlines`.`Flights` (Flight_name,Departure,Arrival,Departure_time,Arrival_time,Seats,Price) VALUES ("SG-640","DEL","CCU","12:00","02:45","100","3500")')
cursor.execute('INSERT INTO `Airlines`.`Flights` (Flight_name,Departure,Arrival,Departure_time,Arrival_time,Seats,Price) VALUES ("SG-650","CCU","MAA","06:00","08:45","100","3580")')
cursor.execute('INSERT INTO `Airlines`.`Flights` (Flight_name,Departure,Arrival,Departure_time,Arrival_time,Seats,Price) VALUES ("AI-720","BEL","CCU","22:00","00:45","100","5500")')
cursor.execute('INSERT INTO `Airlines`.`Flights` (Flight_name,Departure,Arrival,Departure_time,Arrival_time,Seats,Price) VALUES ("SG-790","DEL","BEL","12:00","02:45","100","3500")')
cursor.execute('INSERT INTO `Airlines`.`Flights` (Flight_name,Departure,Arrival,Departure_time,Arrival_time,Seats,Price) VALUES ("AG-590","MAA","CCU","08:00","10:45","100","4500")')
cursor.execute('INSERT INTO `Airlines`.`Flights` (Flight_name,Departure,Arrival,Departure_time,Arrival_time,Seats,Price) VALUES ("SG-525","DEL","MAA","10:00","12:45","100","4500")')
cursor.execute('INSERT INTO `Airlines`.`Flights` (Flight_name,Departure,Arrival,Departure_time,Arrival_time,Seats,Price) VALUES ("AI-530","MAA","DEL","08:00","10:45","100","3580")')
cursor.execute('INSERT INTO `Airlines`.`Flights` (Flight_name,Departure,Arrival,Departure_time,Arrival_time,Seats,Price) VALUES ("AI-523","BEL","MAA","22:00","00:45","100","5500")')
cursor.execute('INSERT INTO `Airlines`.`Flights` (Flight_name,Departure,Arrival,Departure_time,Arrival_time,Seats,Price) VALUES ("AI-540","CCU","DEL","12:00","02:45","100","2500")')
cursor.execute('INSERT INTO `Airlines`.`Flights` (Flight_name,Departure,Arrival,Departure_time,Arrival_time,Seats,Price) VALUES ("SG-530","DEL","MAA","06:00","08:45","100","3580")')
cursor.execute('INSERT INTO `Airlines`.`Flights` (Flight_name,Departure,Arrival,Departure_time,Arrival_time,Seats,Price) VALUES ("AI-500","CCU","BEL","22:00","00:45","100","5500")')
cursor.execute('INSERT INTO `Airlines`.`Flights` (Flight_name,Departure,Arrival,Departure_time,Arrival_time,Seats,Price) VALUES ("SG-540","DEL","CCU","12:00","02:45","100","3500")')
cursor.execute('INSERT INTO `Airlines`.`Flights` (Flight_name,Departure,Arrival,Departure_time,Arrival_time,Seats,Price) VALUES ("AI-550","CCU","MAA","06:00","08:45","100","3580")')
cursor.execute('INSERT INTO `Airlines`.`Flights` (Flight_name,Departure,Arrival,Departure_time,Arrival_time,Seats,Price) VALUES ("AI-520","BEL","CCU","22:00","00:45","100","5500")')
cursor.execute('INSERT INTO `Airlines`.`Flights` (Flight_name,Departure,Arrival,Departure_time,Arrival_time,Seats,Price) VALUES ("SG-590","DEL","BEL","12:00","02:45","100","3500")')
conn.commit()